name: Issues Project
on: 
    issues:
      types: [opened, edited, milestoned]
jobs:
    details:
        runs-on: ubuntu-latest
        steps:
            - name: OutPut GitHub Context
              run: echo "${{ toJson(github) }}"
